# Generated by Django 5.1.4 on 2024-12-28 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='age',
            field=models.DateField(default='2024-12-28'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.DateField(default='2024-12-28'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('road', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
