# Generated by Django 5.1.4 on 2024-12-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_instructor_age_student_age_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
