# Generated by Django 5.1.4 on 2024-12-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_studentcourse_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='buy',
        ),
    ]
