# Generated by Django 5.1.4 on 2024-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_instructor_age_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DateField(),
        ),
    ]
