# Generated by Django 5.1.4 on 2025-01-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_student_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='module',
            name='completed',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='certificate',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
