# Generated by Django 5.1.4 on 2025-01-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='objective',
            field=models.CharField(default=''),
        ),
    ]
