# Generated by Django 5.1.4 on 2025-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='objective',
            field=models.TextField(default=''),
        ),
    ]
