# Generated by Django 5.1.4 on 2025-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_status_alter_studentclass_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='certificate',
            field=models.FileField(upload_to=''),
        ),
    ]
