# Generated by Django 5.1.4 on 2025-03-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_studentcourse_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='certificate',
            field=models.FileField(upload_to='certificates/'),
        ),
    ]
